services:
  api:
    build: .
    container_name: fastapi
    ports:
      - "5000:8000"
    environment:
      - SECRET_KEY=b4m8po9ygfr99po56zsc7774zswvb78ff9d
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - DATABASE_URL=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_ROOT_USER=postgres
      - DATABASE_ROOT_PASSWORD=postgres

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 

    volumes:
      - ./:/usr/src/app:rw

    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
