apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-shared-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.1.9.105
    path: /mnt/pool/k8s
