- name: Setup Docker and Deploy Odoo
  hosts: "{{ target_host }}"
  become: yes

  vars:
    server_ip: "{{ server_ip }}"
    odoo_config_dir: /opt/odoo_config

  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - python3-pip
          - python3-docker
        state: present

    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Create odoo user if not exists
      ansible.builtin.user:
        name: odoo
        shell: /bin/bash
        state: present

    - name: Create Odoo config directory
      ansible.builtin.file:
        path: "{{ odoo_config_dir }}"
        state: directory
        owner: odoo
        group: odoo
        mode: '0755'

    - name: Copy Odoo configuration for remote DB
      ansible.builtin.copy:
        dest: "{{ odoo_config_dir }}/odoo.conf"
        content: |
          [options]
          db_host = {{ server_ip }}
          db_port = 5432
          db_user = odoo
          db_password = odoo
        mode: '0644'

    - name: Pull Odoo image
      community.docker.docker_image:
        name: odoo
        source: pull

    - name: Run Odoo container
      community.docker.docker_container:
        name: odoo
        image: odoo:latest
        restart_policy: always
        volumes:
          - "{{ odoo_config_dir }}/odoo.conf:/etc/odoo/odoo.conf"
        ports:
          - "8069:8069"
        env:
          HOST: "{{ server_ip }}"
        state: started
