- name: Setup Docker and Deploy Odoo
  hosts: "{{ target_host }}"
  become: yes

  vars:
     server_ip: "{{ server_ip }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        cache_valid_time: 3600  

    - name: Download Docker installation script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh

    - name: Install Docker
      shell: sudo sh ./get-docker.sh

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create odoo user if it doesn't exist
      user:
        name: odoo
        shell: /bin/bash
        state: present

    - name: Ensure /opt/odoo directory exists
      file:
        path: /opt/odoo
        state: directory
        owner: odoo
        group: odoo
        mode: '0755'

    - name: Create Odoo config directory
      file:
        path: /opt/odoo_config
        state: directory
        mode: '0755'

    - name: Install pip3 if not already installed
      ansible.builtin.package:
        name: python3-pip
        state: present  
        
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        executable: /usr/bin/pip3

    - name: Copy Odoo configuration with Remote DB
      copy:
        content: |
          [options]
          db_host = {{ server_ip }}
          db_port = 5432
          db_user = odoo
          db_password = odoo
          limit_time_real = 6000
        dest: /opt/odoo_config/odoo.conf
        mode: '0644'

    - name: Run Odoo Container with Remote DB
      community.docker.docker_container:
        name: odoo
        image: odoo
        restart_policy: always
        volumes:
          - "/opt/odoo_config/odoo.conf:/etc/odoo/odoo.conf"
        ports:
          - "8069:8069"