- name: Deploy Odoo in Docker
  hosts: "{{ target_host }}"
  become: yes

  vars:
    server_ip: "{{ server_ip }}"
    odoo_config_dir: /opt/odoo_config

  tasks:

    - name: Create odoo user if not exists
      ansible.builtin.user:
        name: odoo
        shell: /bin/bash
        state: present

    - name: Create Odoo config directory
      ansible.builtin.file:
        path: "{{ odoo_config_dir }}"
        state: directory
        owner: odoo
        group: odoo
        mode: '0755'

    - name: Copy Odoo configuration for remote DB
      ansible.builtin.copy:
        dest: "{{ odoo_config_dir }}/odoo.conf"
        content: |
          [options]
          db_host = {{ server_ip }}
          db_port = 5432
          db_user = odoo
          db_password = odoo
        mode: '0644'

    - name: Pull Odoo image
      community.docker.docker_image:
        name: odoo
        source: pull

    - name: Run Odoo container
      community.docker.docker_container:
        name: odoo
        image: odoo:latest
        restart_policy: always
        volumes:
          - "{{ odoo_config_dir }}/odoo.conf:/etc/odoo/odoo.conf"
        ports:
          - "8069:8069"
        env:
          HOST: "{{ server_ip }}"
        state: started
