name : CI/CD pipline
on: 
  push:
    branches:
        - "main"
jobs:
  build:
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      DATABASE_URL: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_ROOT_USER: ${{ secrets.DATABASE_ROOT_USER }}
      DATABASE_ROOT_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
      TEST_DATABASE_NAME: ${{secrets.TEST_DATABASE_NAME}}
      DO_API_KEY: ${{secrets.DO_API_KEY}}
      VCENTER_HOST: ${{secrets.VCENTER_HOST}}
      VCENTER_USER: ${{secrets.VCENTER_USER}}
      VCENTER_PASSWORD: ${{secrets.VCENTER_PASSWORD}}
      TEMPLATE_NAME: ${{secrets.TEMPLATE_NAME}}
      DATASTORE_NAME: ${{secrets.DATASTORE_NAME}}
      DATACENTER_NAME: ${{secrets.DATACENTER_NAME}}
      ESXI_HOSTNAME: ${{secrets.ESXI_HOSTNAME}} 
      CUSTOMIZATION_SPEC_NAME: ${{secrets.CUSTOMIZATION_SPEC_NAME}}

    services:
      postgres:
        image: postgres
        env:
          DATABASE_ROOT_USER: ${{ secrets.DATABASE_ROOT_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_ROOT_PASSWORD }}
          POSTGRES_DB: ${{secrets.TEST_DATABASE_NAME}}
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest
    steps:
      - name: checking the repository
        uses: actions/checkout@v2
      
      - name: install python v3.10.16
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.16'
      
      - name: update pip
        run: python -m pip install --upgrade pip
      
      - name: installing requirements
        run: |
          

      - name: test with pytest
        run: |
          pip install pytest
          sleep 10
          pytest


      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.USERNAME }}/hybrid_env_fastapi:latest
    
      - name: Log out from Docker Hub
        run: docker logout
